name: Show Artifacts
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v4
    - name: Install PNPM
      uses: pnpm/action-setup@v4
      with: 
        version: 9
    - name: Install Dependencies
      run: pnpm install
    - name: Upload File
      run: mkdir files && cd files && echo Hola Mundo > build-log.txt
      uses: actions/upload-artifact@v4
      with:
        path: files/build-log.txt