name: Job Outputs
on: push
jobs:
  set_output:
    runs-on: ubuntu-latest
    outputs:
      show: ${{ steps.Generate.outputs.deploy-url}}
    steps:
      - id: Generate
        run: echo "deploy-url=https://my-app.example.com" >> "$GITHUB_OUTPUT"
  get_ouput:
    runs-on: ubuntu-latest
    needs: set_output
    steps:
      - env:
        OUTPUT1: ${{ needs.set_output.outputs.show }}
        run: echo "$OUTPUT1"